model:
  target: Models.diffusion.gaussian_diffusion.Diffusion
  params:
    seq_length: 512
    feature_size: 1
    n_layer_enc: 2
    n_layer_dec: 2
    d_model: 128
    timesteps: 2000
    sampling_timesteps: 2000
    loss_type: 'l1'
    beta_schedule: 'cosine'
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.0
    resid_pd: 0.0
    kernel_size: 1
    padding_size: 0

solver:
  base_lr: 1.0e-6
  max_epochs: 20000
  results_folder: .Checkpoints/Checkpoints_fridge
  gradient_accumulate_every: 2
  save_cycle: 2000
  ema:
    decay: 0.995
    update_interval: 10
  
  scheduler:
    target: engine.lr_sch.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 2000
      min_lr: 5.0e-7
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 8.0e-4
      warmup: 500 
      verbose: False

dataloader:
  train_dataset:
    target: Utils.Data_utils.real_datasets.CustomDataset
    params:
      name: Fridge
      proportion: 1.0
      data_root: ./Data/datasets/fridge.csv
      window: 512  # seq_length
      save2npy: True
      neg_one_to_one: True
      seed: 2024
      period: train

  batch_size: 64
  sample_size: 256
  shuffle: False
